import Image from "next/image";
import React from "react";
// import stylex from '@stylexjs/stylex';

const Cards = () => {
  const card = [
    {
      id: 0,
      img: "https://echelon.ai/wp-content/uploads/2023/09/virtual.svg",
      title: "Object detection and tracking",
      content:
        "Our smart Ai based algorithms can identify and track objects in real-time, enabling drones to perform tasks such as surveillance, search and rescue, and inspection with greater accuracy and efficiency.",
    },
    {
      id: 1,
      img: "https://echelon.ai/wp-content/uploads/2023/09/artificial-intelligence.svg",
      title: "Autonomous flight control system",
      content:
        "With autonomous flight control system, drones can fly pre-programmed routes, avoid obstacles, and make real-time adjustments based on environmental conditions.",
    },
    {
      id: 2,
      img: "https://echelon.ai/wp-content/uploads/2023/09/augmented-reality.svg",
      title: "Data analysis and visualization",
      content:
        "Ai driven data analysis and visualization tools enable drone operators to make sense of the vast amounts of data generated by their drones, and extract insights that can inform decision-making.",
    },
  ];
  return (
    <div className="py-20 lg:px-20 px-6  ">
      <div className="space-y-6 text-center  ">
        <p>WHAT WE DO</p>
        <h1 className="text-3xl font-bold">
          As pioneers in the drone technology landscape, we provide cutting-edge
          solutions designed for today’s complex challenges.
        </h1>
        <p className="text-md">
          Our objective is to utilize swarm technology to deliver the precision
          and efficiency that our clients require for the successful completion
          of their initiatives. We are committed to enhancing businesses and
          bettering lives through cutting-edge drone swarm technologies and AI
          solutions.
        </p>
      </div>
      <div className=" grid lg:grid-cols-3 md:grid-cols-2 gap-8 mt-10 ">
        {card.map((crd) => {
          return (
            <div
              key={crd.id}
              className="grid gap-3 text-center p-5 rounded shadow-md border"
            >
              <div className="mx-auto">
                <Image
                  src={crd.img}
                  alt={crd.img}
                  width={55}
                  height={55}
                  className="bg-gray-300 rounded-full p-2"
                />
              </div>
              <h1 className="text-xl font-bold">{crd.title}</h1>
              <p>{crd.content}</p>
            </div>
          );
        })}
      </div>
      {/* <div {...stylex.props(cardStyles.cardWrapper)}>
        {card.map((crd) => {
          return (
            <div key={crd.id} {...stylex.props(cardStyles.cardContainer)}>
              <h1 {...stylex.props(cardStyles.cardTitle)}>{crd.title}</h1>
              <p {...stylex.props(cardStyles.cardContent)}>{crd.content}</p>
            </div>
          );
        })}
      </div> */}
    </div>
  );
};

export default Cards;

// const MOBILE = '@media (max-width: 700px)';
// const cardStyles = stylex.create({
//   cardWrapper: {
//     display: {
//       default: 'flex',
//       [MOBILE]: 'block',
//     },
//     gap: {
//       default: '2rem',
//       [MOBILE]: '1rem',
//     },
//     // marginTop: '2rem',
//   },
//   cardContainer: {
//     display: 'grid',
//     placeItems: 'center',
//     // gap: '2rem',
//     // gap: {
//     //   default: '2rem',
//     //   [MOBILE]: '1rem',
//     // },
//     border: '1px solid gray',
//     borderRadius: '3px',
//     padding: '10px',
//     marginBottom: '1rem',
//   },
//   cardTitle: {
//     fontSize: '1.5rem',
//   },
//   cardContent: {
//     fontSize: '1rem',
//   },
// });
